name: Docs

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          recurse: true
          template: minami
          front_page: README.md
          output_dir: ./out

      - run: ls out
